### ISSUE TITLE
Bug: uncaught panic error when incorrect cursor is supplied

### ISSUE THREAD

**Issue by captchanjack** [cloudmatelabs/gorm-gqlgen-relay#12]
When a before/after cursor is supplied to a query with a different set of orderBy keys, the `loadCursor` will panic because there is a mismatch in map keys.

![image](https://github.com/cloudmatelabs/gorm-gqlgen-relay/assets/53301102/bd782e94-05d3-470f-9b2c-a886c21e1a40)

In the screenshot you can see if the cursor deserialises and has keys that are not within the orderBy map then the string conversion will panic

**Comment by captchanjack** [comment]
Raised a PR!

**Comment by captchanjack** [comment]
@juunini Hello! Is there any chance you could take a look at this PR?

**Comment by juunini** [comment]
Oh, sorry, I was too late to see this issue and PR
