### ISSUE TITLE
Bug: Errors when table/column/field names are not lower case (e.g. camelCase)

### ISSUE THREAD

**Issue by captchanjack** [cloudmatelabs/gorm-gqlgen-relay#3]
Hey, just wanted to say thanks for writing this package, works really well with gorm and gqlgen together.

I've identified some issues when DB table and column names are not lower case/snake case and instead case sensitive.

In these files you're constructing the statements without wrapping table/field names around quotes:
a. order > traverse.go
b. cursor > after_before.go
c. where > traverse.go

for example; selecting displayName from the User table should look like:
```
"User"."displayName"
```

Also in cursor > cursor.go:

the function fieldWithColumnIsEqual fails if the names are case sensitive, the string comparison should look something like this:

```
strings.ToLower(key) == strings.ReplaceAll(strings.ToLower(field))
```

**Comment by juunini** [comment]
Merge your pull request. thanks!
