### ISSUE TITLE
Request: Would be good if we could set the schema name from the Paginate API

### ISSUE THREAD

**Issue by captchanjack** [cloudmatelabs/gorm-gqlgen-relay#4]
When we're not using the default "public" schema (in the case of postgresql), it would be good if the relay.Paginate function accepted options to set schema name

Alternatively, the relay.Paginate function could just inherit settings from the *gorm.DB object

**Comment by juunini** [comment]
Good request.  
I'll be soon add that option.

**Comment by juunini** [comment]
This request is accepted by #9
