### ISSUE TITLE
Bug: Total Count does not consider where filters

### ISSUE THREAD

**Issue by captchanjack** [cloudmatelabs/gorm-gqlgen-relay#6]
Found that total count query does not consider where filters when they are provided. this has an impact on the hasNextPage field

Have fixed this in the same PR #5

<img width="567" alt="image" src="https://github.com/cloudmatelabs/gorm-gqlgen-relay/assets/53301102/8e784e39-461d-42ba-b788-ff945220e29d">

**Comment by juunini** [comment]
Merge your pull request. thanks!
